import * as Yup from "yup"

export const QR_CODE_TYPES = [
  { value: "store", label: "Store" },
  { value: "device", label: "Device" },
  { value: "order", label: "Order" },
]

// Create validation - only type is required (reference is auto-generated)
export const qrCodeCreateValidationSchema = Yup.object({
  type: Yup.string().required("Type is required"),
  quantity: Yup.number()
    .required("Quantity is required")
    .min(1, "Quantity must be at least 1")
    .max(100, "Quantity cannot exceed 100")
    .typeError("Quantity must be a number"),
})

// Edit validation - all fields optional (sometimes rule)
export const qrCodeUpdateValidationSchema = Yup.object({
  type: Yup.string(),
  status: Yup.string().oneOf(["active", "inactive"]),
})

// For backwards compatibility
export const qrCodeValidationSchema = qrCodeCreateValidationSchema

// Create form fields (no reference field - auto-generated by API)
export const qrCodeCreateFormFields = [
  {
    name: "type",
    label: "Type",
    type: "select" as const,
    required: true,
    placeholder: "Select QR code type",
    options: QR_CODE_TYPES,
  },
  {
    name: "quantity",
    label: "Quantity",
    type: "number" as const,
    required: true,
    placeholder: "Enter quantity (1-100)",
    min: 1,
    max: 100,
  },
]

export const QR_CODE_STATUSES = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
]

// Edit form fields (all optional)
export const qrCodeEditFormFields = [
  {
    name: "type",
    label: "Type",
    type: "select" as const,
    required: false,
    placeholder: "Select QR code type",
    options: QR_CODE_TYPES,
  },
  {
    name: "status",
    label: "Status",
    type: "select" as const,
    required: false,
    placeholder: "Select status",
    options: QR_CODE_STATUSES,
  },
]

// For backwards compatibility
export const qrCodeFormFields = qrCodeCreateFormFields

export type QRCodeFormValues = {
  type: "store" | "device" | "order" | ""
  quantity: number
}

export type QRCodeEditFormValues = {
  type: "store" | "device" | "order" | ""
  status: "active" | "inactive" | ""
}
