"use client"

import UserForm from "@/components/dashboard/UserForm"
import ViewPageHeader from "@/components/dashboard/ViewPageHeader"
import { catchError } from "@/lib/utils"
import { useCreateQrCodeMutation } from "@/store/qr-codes"
import { useRouter } from "next/navigation"
import {
  qrCodeCreateValidationSchema,
  qrCodeCreateFormFields,
  type QRCodeFormValues,
} from "../qr-code-form-config"
import { toast } from "@/hooks/use-toast"

export default function CreateQrCodePage() {
  const router = useRouter()
  const [createQrCode, { isLoading }] = useCreateQrCodeMutation()

  const initialValues: QRCodeFormValues = {
    type: "",
    quantity: 1,
  }

  const handleSubmit = async (values: QRCodeFormValues, helpers: any) => {
    try {
      // Submit only type and quantity - reference is auto-generated by API
      await createQrCode({
        type: values.type as "store" | "device" | "order",
        // reference is auto-generated by the API
        quantity: values.quantity,
      }).unwrap()
      toast({
        title: "Success",
        description: "QR code created successfully",
      })
      helpers.resetForm()
      router.push("/dashboard/qr-codes")
    } catch (error: any) {
      catchError(error, helpers.setFieldError)
    } finally {
      helpers.setSubmitting(false)
    }
  }

  return (
    <div>
      <ViewPageHeader title="Create QR Code" />
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div>
          <UserForm
            title="QR Code Details"
            description="Create a new QR code. Reference will be auto-generated."
            initialValues={initialValues}
            validationSchema={qrCodeCreateValidationSchema}
            fields={qrCodeCreateFormFields as any}
            isLoading={isLoading}
            onSubmit={handleSubmit}
            submitLabel="Create QR Code"
            onCancel={() => router.push("/dashboard/qr-codes")}
          />
        </div>
        <div>
          <div className="bg-white rounded-lg border p-6 h-full flex flex-col justify-center items-center text-center">
            <div className="text-sm text-muted-foreground">
              <p className="mb-2">QR code preview will be generated after creation</p>
              <p>The reference will be auto-generated by the system</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
