name: Webapp Pipeline

run-name: |
  ${{ 
    github.ref == 'refs/heads/prod' && 'Deploy to Prod' ||
    github.ref == 'refs/heads/stage' && 'Deploy to Stage' ||
    github.ref == 'refs/heads/dev' && 'Deploy to Dev' ||
    'Running CI '
  }} by @${{ github.actor }}

on:
  push:
    branches: ["dev", "stage", "prod", feature/*, bugfix/*, fix/*]
  pull_request:
    branches: [prod, dev, stage]

env:
  project: "depleteiq"
  application: "webapp"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Buld and Test
    runs-on: runner
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint (check only)
        run: pnpm lint
        continue-on-error: true # Don't fail on lint errors

      - name: Type check
        run: pnpm type-check
        continue-on-error: true
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build
        run: pnpm build

  deploy:
    name: Deploy to Server
    runs-on: runner
    # Requires successful build and test
    needs: build_and_test
    # Run job if branch is prod, stage and dev
    if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/dev'
    # Set environment for job based on branch
    environment: ${{  github.ref == 'refs/heads/prod' && 'prod' || github.ref == 'refs/heads/stage' && 'stage' || 'dev' }}
    # Set stage variable to branch name
    env:
      stage: ${{  github.ref == 'refs/heads/prod' && 'prod' || github.ref == 'refs/heads/stage' && 'stage' || 'dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Install Ansible
        if: startsWith(runner.name, 'GitHub Actions')
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible --version

      # Download terraform state file and set vm_ips output to environment variable
      - name: Get terraform state for VM IPs
        id: ip_output
        run: |
          aws s3 cp "s3://${S3_BUCKET}/${STATE_KEY}" terraform.tfstate
          echo "vm_ips=$(terraform output -json vm_ips)" >> $GITHUB_OUTPUT
          rm terraform.tfstate
        env:
          STATE_KEY: "terraform-orbit/${{ env.project }}/${{ env.stage }}/terraform.tfstate"
          S3_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        # Create .env, docker-compose and nginx file from Secrets and replace placeholders
      - name: Populate .env and docker-compose and nginx file
        run: |
          echo "Writing .env from GitHub Secret..."

          cat > .env.production << 'EOF'
          ${{ secrets.ENV_FILE }}
          EOF

          echo "Writing nginx config file"
          cat > nginx.conf << 'EOF'
          ${{ secrets.NGINX_CONFIG }}
          EOF

          echo "Writing ecosystem config file"
          cat > ecosystem.config.js << 'EOF'
          ${{ secrets.ECO_CONFIG }}
          EOF
           
          # Get every VM IPs for API servers
          API_IP=$(echo '${{ steps.ip_output.outputs.vm_ips }}' | jq -r '[to_entries[] | select(.key | contains("-api-")) | .value] | join(" ")')
          WEBAPP_IP=$(echo '${{ steps.ip_output.outputs.vm_ips }}' | jq -r '[to_entries[] | select(.key | contains("-webapp-")) | .value] | join(" ")')

          # Replace the placeholders in .env.production
          sed -i "s/__APP_URL__/$WEBAPP_IP/g" .env.production
          sed -i "s/__API_URL__/$API_IP/g" .env.production

          # Replace the placeholder in nginx.conf
          sed -i "s/__NGINX_SERVER_HOST__/$WEBAPP_IP/g" nginx.conf

          echo API_IP is $API_IP
          echo WEBAPP_IP is $WEBAPP_IP

      #  SSH key setup with passphrase
      - name: Setup SSH key with Passphrase
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # This bypasses the need for a real terminal (TTY)
          cat << 'EOF' > ~/.ssh/askpass.sh
          #!/bin/bash
          echo "${SSH_KEY_PASSPHRASE}"
          EOF
          chmod +x ~/.ssh/askpass.sh

          export DISPLAY=:0
          export SSH_ASKPASS=~/.ssh/askpass.sh
          export SSH_KEY_PASSPHRASE="${SSH_KEY_PASSPHRASE}"

          # Force ssh-add to use askpass by redirecting input from /dev/null
          ssh-add ~/.ssh/id_rsa < /dev/null

          rm ~/.ssh/askpass.sh
          ssh-add -l

          # 6. Add IPs to known_hosts
          for ip in $(echo '${{ steps.ip_output.outputs.vm_ips }}' | jq -r '.[]'); do
            ssh-keyscan -H $ip >> ~/.ssh/known_hosts 2>/dev/null || true
          done

      # Checking SSHworks with passphrase
      - name: Test SSH Connection
        run: |
          echo "Testing SSH connections..."
          for ip in $(echo '${{ steps.ip_output.outputs.vm_ips }}' | jq -r '.[]'); do
            echo "Testing connection to $ip..."
            ssh -o StrictHostKeyChecking=no root@$ip "echo 'SSH to $ip successful'" || echo "Failed to connect to $ip"
          done

      # Dynamically create Ansible Inventory for runbooks
      - name: Create Ansible Inventory
        run: |
          cat > inventory.ini << EOF
          [all:vars]
          ansible_user=${SSH_USER}
          ansible_ssh_common_args=-o StrictHostKeyChecking=no
          ansible_python_interpreter=/usr/bin/python3

          [webapp]
          EOF

          # Add WEBAPP servers filtered by VM_NAME
          echo '${{ steps.ip_output.outputs.vm_ips }}' | jq -r \
            'to_entries[] | 
            select(.key | contains("-webapp-")) | 
            "\(.key) ansible_host=\(.value)"' >> inventory.ini

          # Add the final part
          cat >> inventory.ini << 'EOF'

          [droplets:children]
          webapp
          EOF

          echo "Generated Ansible Inventory:"
          cat inventory.ini
        env:
          vm_name: "${{ env.project }}-${{ env.application }}"
          SSH_USER: ${{ secrets.SSH_USER }}

      #  Executre code backup on server with ansible
      # - name: Run Code Backup
      #   run: ansible-playbook -i inventory.ini .github/workflows/ansible/backup.yml
      #   env:
      #     PROJECT: "${{ env.project }}-${{ env.application }}"
      #     SSH_USER: ${{ secrets.SSH_USER }}

      - name: Run Code Backup to S3
        run: ansible-playbook -i inventory.ini .github/workflows/ansible/backup-s3.yml
        env:
          PROJECT: "${{ env.project }}-${{ env.application }}"
          SSH_USER: ${{ secrets.SSH_USER }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: ${{ env.stage }}
          retention: 5

      # Deploy latest changes to server with ansible
      - name: Deploy App
        run: ansible-playbook -i inventory.ini .github/workflows/ansible/deploy.yml
        env:
          PROJECT: "${{ env.project }}-${{ env.application }}"
          SSH_USER: ${{ secrets.SSH_USER }}
          app_container: ${{ secrets.APP_CONTAINER }}
          nginx_container: ${{ secrets.NGINX_CONTAINER }}
          postgres_container: ${{ secrets.POSTGRES_CONTAINER }}
          SOURCE_DIR: ${{ github.workspace }}
          SSL_EMAIL: ${{ secrets.SSL_EMAIL }}
          DOMAIN_NAMES: ${{ secrets.DOMAIN_NAMES }}
